### ISSUE TITLE
How your project differ from Pandoc/markdown/... table projects?

### ISSUE THREAD

**Issue by sami10007** [JDMCreator/Table.js#1]
Hi, 

The package `markdown` tries to improve still table use with LaTeX, since "Lunamark [has Markdown syntax extensions for tables [in roadmap]". Can you please explain how your targets compare to the project mentioned here? https://tex.stackexchange.com/a/334851/13173

I tried once unsuccessfully Pandoc tables in LaTeX for helping note taking: https://stackoverflow.com/a/32769985/54964 but discontinued because I found too cumbersome in the end. 

To have a standalone tool to work with tables would be sufficient. Second target can be online tool, but not necessary. Can you provide some more examples what you are trying to do? It sounds to me that you are trying to convert from Pandoc/markdown/... tables to LaTeX tables.  

Best regards, 

Sami

**Comment by JDMCreator** [comment]
Hi, I close this issue because it is related to another of my projects (LaTeX Table Editor) which is based on this Javascript project.
